// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCavio8b5oKKkNZbW-maOKfsuBxpBu-3S4',
    appId: '1:21739793114:web:6c4e7f77df221cc31653e3',
    messagingSenderId: '21739793114',
    projectId: 'rattil-quran-app',
    authDomain: 'rattil-quran-app.firebaseapp.com',
    storageBucket: 'rattil-quran-app.firebasestorage.app',
    measurementId: 'G-5QEBDCFTEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEimTL2-n9LWX8K93pxjDkQh0vlRzX_SQ',
    appId: '1:21739793114:android:8b4e9b252a7050e21653e3',
    messagingSenderId: '21739793114',
    projectId: 'rattil-quran-app',
    storageBucket: 'rattil-quran-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIt1vS5kINEA9yd_4Mckga9OKvKW8mboU',
    appId: '1:21739793114:ios:1afdf10c8c5a210d1653e3',
    messagingSenderId: '21739793114',
    projectId: 'rattil-quran-app',
    storageBucket: 'rattil-quran-app.firebasestorage.app',
    iosBundleId: 'com.hexait.rattil',
  );
}
